from __future__ import annotations

import argparse
import re
import sqlite3
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SQL_DIR = PROJECT_ROOT / "sql"
PROCESSED = PROJECT_ROOT / "data" / "processed"
DB_PATH = PROCESSED / "olist.db"
REPORT_PATH = PROJECT_ROOT / "reports" / "sql_query_results.md"

#: cleaned parquet file -> database table name
TABLE_MAP = {
    "customers_clean": "customers",
    "products_clean": "products",
    "sellers_clean": "sellers",
    "geolocation_clean": "geolocation",
    "orders_clean": "orders",
    "order_items_clean": "order_items",
    "payments_clean": "payments",
    "reviews_clean": "reviews",
}

QUERY_FILES = [
    "revenue_analysis.sql",
    "customer_analysis.sql",
    "product_analysis.sql",
    "marketing_analysis.sql",
]


def _prepare(df: pd.DataFrame) -> pd.DataFrame:
    """Make a cleaned DataFrame safe for SQLite: ISO dates, int booleans."""
    out = df.copy()
    for col in out.columns:
        s = out[col]
        if pd.api.types.is_datetime64_any_dtype(s):
            out[col] = s.dt.strftime("%Y-%m-%d %H:%M:%S")
        elif pd.api.types.is_bool_dtype(s):
            out[col] = s.astype("int8")
        elif isinstance(s.dtype, pd.CategoricalDtype):
            out[col] = s.astype(str)
        elif s.dtype == object and len(s) and isinstance(s.dropna().iloc[0] if s.notna().any() else None, __import__("datetime").date):
            out[col] = s.astype(str)
    return out


def build_database(db_path: Path = DB_PATH) -> sqlite3.Connection:
    """Create the schema and load the Phase 3 cleaned tables into it."""
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists():
        db_path.unlink()

    conn = sqlite3.connect(db_path)
    conn.executescript((SQL_DIR / "schema.sql").read_text(encoding="utf-8"))

    for parquet_name, table in TABLE_MAP.items():
        df = pd.read_parquet(PROCESSED / f"{parquet_name}.parquet")
        cols = [r[1] for r in conn.execute(f"PRAGMA table_info({table})")]
        df = _prepare(df)[[c for c in cols if c in df.columns]]
        df.to_sql(table, conn, if_exists="append", index=False)
        print(f"  loaded {table:14s} {len(df):>9,} rows")

    # Give the query planner column statistics. Without ANALYZE, SQLite picks
    # poor join orders for the multi-table analysis views and every query pays
    # several seconds for the same join.
    conn.execute("ANALYZE")
    conn.commit()
    return conn


def split_queries(sql_text: str) -> list[tuple[str, str]]:
    """Split a .sql file on ``-- name: <id>`` markers."""
    parts = re.split(r"^--\s*name:\s*(\w+)\s*$", sql_text, flags=re.MULTILINE)
    out = []
    for i in range(1, len(parts), 2):
        name, body = parts[i], parts[i + 1]
        body = "\n".join(l for l in body.splitlines() if not l.strip().startswith("--")).strip()
        if body:
            out.append((name, body.rstrip(";")))
    return out


def run_all(conn: sqlite3.Connection, max_rows: int = 12, to_report: bool = False) -> None:
    """Execute every query and print its result."""
    chunks: list[str] = []
    pd.set_option("display.width", 200)
    pd.set_option("display.max_columns", 40)
    pd.set_option("display.float_format", lambda v: f"{v:,.2f}")

    for fname in QUERY_FILES:
        text = (SQL_DIR / fname).read_text(encoding="utf-8")
        queries = split_queries(text)
        header = f"\n{'=' * 100}\n{fname}  —  {len(queries)} queries\n{'=' * 100}"
        print(header)
        chunks.append(f"\n## `{fname}`\n")

        for name, body in queries:
            print(f"\n--- {name} " + "-" * (92 - len(name)))
            try:
                df = pd.read_sql_query(body, conn)
            except Exception as exc:  # surface the failing query rather than hiding it
                print(f"  ERROR: {exc}")
                chunks.append(f"\n### `{name}`\n\n**FAILED:** {exc}\n")
                continue
            shown = df.head(max_rows)
            print(shown.to_string(index=False))
            if len(df) > max_rows:
                print(f"  ... {len(df) - max_rows} more rows")
            chunks.append(
                f"\n### `{name}`\n\n```sql\n{body}\n```\n\n"
                f"**Result** ({len(df)} rows{', first ' + str(max_rows) + ' shown' if len(df) > max_rows else ''}):\n\n"
                f"{shown.to_markdown(index=False)}\n"
            )

    if to_report:
        REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        REPORT_PATH.write_text(
            "# SQL query results\n\n"
            "Generated by `sql/build_db.py`. Engine: SQLite (see the README's tech stack "
            "section for why, and for the PostgreSQL portability note).\n\n"
            "Analysis base for every query: delivered orders, 2017-01-01 to 2018-08-31.\n"
            + "".join(chunks),
            encoding="utf-8",
        )
        print(f"\nWrote {REPORT_PATH}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", action="store_true", help="write reports/sql_query_results.md")
    ap.add_argument("--max-rows", type=int, default=12)
    args = ap.parse_args()

    print(f"SQLite {sqlite3.sqlite_version} -> {DB_PATH}")
    conn = build_database()
    size = DB_PATH.stat().st_size / 1024**2
    print(f"\nDatabase built ({size:.1f} MB)\n")
    run_all(conn, max_rows=args.max_rows, to_report=args.report)
    conn.close()


if __name__ == "__main__":
    main()
